- name: Get Vector distrib
  ansible.builtin.get_url:
    url: https://packages.timber.io/vector/0.35.0/vector-0.35.0-1.x86_64.rpm
    dest: /home/leo/vector-0.35.0-1.x86_64.rpm
    mode: "0755"
- name: Install Vector
  become: true
  remote_user: leo
  ansible.builtin.copy:
    remote_src: true
    src: "/home/leo/"
    dest: "/usr/bin/"
    mode: "0755"
    owner: root
    group: root
- name: Create Vector directory
  become: true
  ansible.builtin.file:
    path: "/etc/vector"
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Vector | Template config
  become: true
  ansible.builtin.template:
    src: template/vector.j2
    dest: /etc/vector/vector.yml
    mode: "0755"
    owner: root
    group: root
- name: Vector | Create systemd unit
  become: true
  ansible.builtin.template:
    src: template/vector.j2
    dest: /etc/systemd/system/vector.service
    mode: "0755"
    owner: root
    group: root
  notify: Start Vector

