---
# handlers file for vector-role

- name: Start Vector
  remote_user: leo
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: false
    name: vector.service
    state: restarted
