- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Include vector role
      include_role:
        name: vector-role

    - name: Check vector service
      assert:
        that: vector_pid.stdout != 0
        success_msg: "Service is running"
        fail_msg: "Service not running"

    - name: Check vector config
      assert:
        that: valid_config.rc == 0
        success_msg: "Config valid"
        fail_msg: "Config not valid "
